apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ebstesting1"

  links:
    - url: https://github.com/RohanAwasthi/testforgcp100
      title: "ebstesting1"
      icon: code

  labels:
    system: web-apps
    environmentname: envforgcp

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-ebstesting1'
    github.com/project-slug: RohanAwasthi/testforgcp100
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
